FROM node:16

WORKDIR /app
COPY frontend/dist/ ./frontend/dist/
COPY backend/src/ ./backend/src/
COPY backend/package.json ./backend/package.json
COPY backend/package-lock.json ./backend/package-lock.json
RUN cd backend && npm install

ENV PORT 8080
ENV NODE_ENV production
ENV NODE_NAME http://example.com

ENTRYPOINT node ./backend/src/index.js
